# -*- coding: utf-8 -*-
"""WebScraping-Shopee.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E1nwoa4l7EplEfXCP1xSRbEI9lbwRINM
"""

# set up libraries
#!pip install selenium
#!apt-get update
#!apt install chromium-chromedriver # <-- pip install chromedriver_installer
#!cp /usr/lib/chromium-browser/chromedriver /usr/bin 
import sys 
sys.path.insert(0, '/usr/lib/chromium-browser/chromedriver')

# set up environment
from selenium import webdriver 
from selenium.webdriver.common.keys import Keys 
import pandas as pd
#ถ้า run บนเครื่องไม่ต้องใส่ option นี้
chrome_options = webdriver.ChromeOptions()
#ไม่ต้องเปิด Chrome ขึ้นมา
chrome_options.add_argument('--headless')
chrome_options.add_argument('--no-sandbox')
driver = webdriver.Chrome('chromedriver', chrome_options=chrome_options)

URL = 'https://shopee.co.th/'

driver.get(URL)

driver.page_source

# search for a bag then hit enter on keyboard
driver.find_element_by_class_name('shopee-searchbar-input__input').send_keys('กระเป๋า' + Keys.ENTER)

list_product = driver.find_elements_by_class_name('PFM7lj')

list_product[0].text

list_product_text = [item.text for item in list_product]

list_product_text[:10]

# get price
list_price = driver.find_elements_by_class_name('_32hnQt')

# list comprehension for price
list_price_text = [item.text for item in list_price]
print(list_price_text[:10])

# create a dataframe product and price
df = pd.DataFrame(zip(list_product_text, list_price_text), columns = ['Product', 'Price'])
df.head()

df.to_csv('Shopee_Bags_Price.csv')