# -*- coding: utf-8 -*-
"""WebScraping-Covid.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DiPaaaIdnhxIZdT4n9bKZfo_WtrvBtr2

# BeautifulSoup

From VS code have to install
pip install beautifulsoup4
pip install requests
pip install pandas

Run pythonw แทน python จะสามารถ run background ใน task scheduler ได้
"""

#Initial Library
from bs4 import BeautifulSoup
import requests
import pandas as pd
from datetime import date

#Initial Variable
MY_URL = "https://www.worldometers.info/coronavirus/"
page = requests.get(MY_URL)
#soup = BeautifulSoup(page.text, 'html5lib') #<-- Notwork 'html5lib'
soup = BeautifulSoup(page.text, 'html.parser')
soup.find_all('h1')

table_header = soup.select('#main_table_countries_today thead tr')

# List comprehension
header = [th.text.strip() for th in table_header[0]('th')]

#header

table_rows = soup.select('#main_table_countries_today tbody tr')

rows_list = []
for tr in table_rows:
  row = [td.text.strip() for td in tr('td')]
  rows_list.append(row)

  #print(rows_list[:3])

# create a new dataframe
df = pd.DataFrame(rows_list, columns= header)
#df.head()

df[df["Country,Other"] == 'Thailand']

#df.info()

df['TotalCases'] = df['TotalCases'].str.replace(',', '').astype('int')
#df['NewCases'] = df['NewCases'].str.replace(',', '').astype('int')
#df.head()

df = df.rename(columns = {'Country,Other':'country'})

"""# Line Nofify"""

# get first values
Country = df.query("country == 'Thailand'")['country'].values[0]
Newcases = df.query("country == 'Thailand'")['NewCases'].values[0]
Totalcases = df.query("country == 'Thailand'")['TotalCases'].values[0]

Country, Newcases, Totalcases

line_token = "HhG4msoF97WxSEqxY2R8ru0MN4gbJbWAtDhhPPqM4P1"

def line_notify(message, token):
  """[summary]

  Args:
      message ([type]): [description]
      token ([type]): [description]

  Returns:
      [type]: [description]
  """
  url = "https://notify-api.line.me/api/notify"
  data = ({'message': message})
  LINE_HEADERS = {"Authorization": "Bearer " + token}
  session = requests.Session()
  response = session.post(url, headers=LINE_HEADERS, data = data)
  return response

today = date.today()
response = line_notify('\nผู้ติดเชื้อ Covid ของประเทศไทย วันที่ ' + today.strftime("%d/%m/%Y") + '\nรายใหม่ จำนวน ' + str(Newcases) + ' รวม ' + str(Totalcases), line_token)
